[phases.setup]
nixPkgs = ["php82", "php82Extensions.curl", "php82Extensions.mbstring", "php82Extensions.openssl"]

[phases.install]

[phases.build]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} router.php"
